# Generated by Django 5.1.4 on 2024-12-28 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.CharField(max_length=150, unique=True, verbose_name='Ник в Телеграме')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание вопроса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления')),
                ('chatgpt_response', models.TextField(blank=True, null=True, verbose_name='Ответ от ChatGPT')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app1.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание запроса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления')),
                ('chatgpt_response', models.TextField(blank=True, null=True, verbose_name='Ответ от ChatGPT')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='app1.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение жалобы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Решено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='app1.user', verbose_name='Пользователь')),
            ],
        ),
    ]
